@startuml
!include ../utm_fims_arch_seq_style.puml

actor USS as U

participant "FIMS-Ops-Controller" as FOC
participant "FIMS-Authz" as FA
participant "FIMS-Ops-Proposals-Gateway" as FOPG
participant "FIMS-Ops-Proposals-Handler" as FOPH
participant "FIMS-Ops-Proposals-Data" as FOPD
participant "FIMS-Ops-Proposals-Responder" as FOPR
participant "FIMS-Ops-Messenger" as FOM

U -> FOM: subscribe to my topic
U -> FOC: submit Operation\nvia HTTPS POST
activate FOC
FOC -> FA: check auth

activate FA
FA -> FA: check
FA -> FOC: auth OK
deactivate FA

FOC -> FOC: validate JSON input

FOC -> FOPG: check submission


activate FOPG
FOPG -> FOPG: validate request
FOPG -> FOPG: assign UUID to op
FOPG -> FOC: HTTP 202 with UUID
FOC -> U: HTTP 202 with UUID
deactivate FOC

FOPG -> FOPH: check submission
deactivate FOPG
activate FOPH
FOPH -> FOPH: check
FOPH -> FOPD: store result
activate FOPD
FOPD -> FOPD: store
FOPD -> FOPH: success
deactivate FOPD

FOPH -> FOPR: result of check
deactivate FOPH
activate FOPR
FOPR -> FOPR: format response
FOPR -> FOM: send response
deactivate FOPR


activate FOM
FOM -> FOM: create messages
FOM -> FOM: identify addressees
FOM -> U: "operation thumbs up" to topic
deactivate FOM


@enduml
