@startuml
!include ../utm_fims_arch_seq_style.puml

actor USS as U

participant "FIMS-Ops" as FO
participant "FIMS-Authz" as FA

U -> FO: submit Operation\nvia HTTPS POST
activate FO
FO -> FA: check auth

activate FA
FA -> FA: check
FA -> FO: auth OK
deactivate FA

FO -> FO: validate JSON input
FO -> U: HTTP 202
FO -> FO: check submission
FO -> U: operation thumbs up
deactivate FO


@enduml
