' Project      : NASA UTM
' Author       : Joseph Rios, joseph.l.rios@nasa.gov
' First version: 19 May 2017

@startuml
!include ../utm_fims_arch_seq_style.puml

participant USS as U
participant "FIMS-Disc-Messenger" as FDM
participant "FIMS-Authz" as FA

title USS Discovery Subscription\n\
VERSION_STAMP

note over U
    note that "USS" may
    represent a USS Instance
    or another system run
    by the USS. The USS may
    subscribe multiple times
    with different parameters,
    perhaps limited to the number
    of Instances currently
    registered by this USS.
end note

autonumber
U -> FDM : submit subscription request
activate FDM
FDM -> FA: check auth

activate FA
FA -> FA: check
FA --> FDM: auth OK
deactivate FA

FDM --> U : subscription created, connected

deactivate FDM


@enduml