' Project      : NASA UTM
' Author       : Joseph Rios, joseph.l.rios@nasa.gov
' First version: 19 May 2017

@startuml
!include ../utm_fims_arch_seq_style.puml


participant "USS Instance" as I
participant "USS-Discovery" as FD
participant "FIMS-Authz" as FA

title USS Discovery Registration\n\
VERSION_STAMP

autonumber

I -> FD : submit registration data
activate FD

FD -> FA: check auth

activate FA
FA -> FA: check
FA --> FD: auth OK
deactivate FA
FD -> FD: validate JSON input
FD --> I : HTTP 200
deactivate FD


FD -> I  : notify of new registration\nvia POST
note over I, FD #aqua
    If the instance does not
    return HTTP 200, the instance
    will not be registered and the
    sequence would end.
end note
I  --> FD: HTTP 200
FD -> FD: store registration data



@enduml