swagger: '2.0'
info:
  description: >-
    This API describes the minimum interface that a USS must implement to  be
    part of the USS Network.  This API allows for communication of data  between
    USS Instances and from FIMS to a USS regarding new USS Instances.
  version: v4
  title: USS Required API
  termsOfService: >

    A. No Warranty: THE SUBJECT SOFTWARE IS PROVIDED "AS IS" WITHOUT ANY
    WARRANTY OF ANY KIND, EITHER EXPRESSED, IMPLIED, OR STATUTORY, INCLUDING,
    BUT NOT LIMITED TO, ANY WARRANTY THAT THE SUBJECT SOFTWARE WILL CONFORM TO
    SPECIFICATIONS, ANY IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
    PARTICULAR PURPOSE, OR FREEDOM FROM INFRINGEMENT, ANY WARRANTY THAT THE
    SUBJECT SOFTWARE WILL BE ERROR FREE, OR ANY WARRANTY THAT DOCUMENTATION, IF
    PROVIDED, WILL CONFORM TO THE SUBJECT SOFTWARE. THIS AGREEMENT DOES NOT, IN
    ANY MANNER, CONSTITUTE AN ENDORSEMENT BY GOVERNMENT AGENCY OR ANY PRIOR
    RECIPIENT OF ANY RESULTS, RESULTING DESIGNS, HARDWARE, SOFTWARE PRODUCTS OR
    ANY OTHER APPLICATIONS RESULTING FROM USE OF THE SUBJECT SOFTWARE. FURTHER,
    GOVERNMENT AGENCY DISCLAIMS ALL WARRANTIES AND LIABILITIES REGARDING
    THIRD-PARTY SOFTWARE, IF PRESENT IN THE ORIGINAL SOFTWARE, AND DISTRIBUTES
    IT "AS IS."


    B. Waiver and Indemnity: RECIPIENT AGREES TO WAIVE ANY AND ALL CLAIMS
    AGAINST THE UNITED STATES GOVERNMENT, ITS CONTRACTORS AND SUBCONTRACTORS, AS
    WELL AS ANY PRIOR RECIPIENT. IF RECIPIENT''S USE OF THE SUBJECT SOFTWARE
    RESULTS IN ANY LIABILITIES, DEMANDS, DAMAGES, EXPENSES OR LOSSES ARISING
    FROM SUCH USE, INCLUDING ANY DAMAGES FROM PRODUCTS BASED ON, OR RESULTING
    FROM, RECIPIENT''S USE OF THE SUBJECT SOFTWARE, RECIPIENT SHALL INDEMNIFY
    AND HOLD HARMLESS THE UNITED STATES GOVERNMENT, ITS CONTRACTORS AND
    SUBCONTRACTORS, AS WELL AS ANY PRIOR RECIPIENT, TO THE EXTENT PERMITTED BY
    LAW. RECIPIENT''S SOLE REMEDY FOR ANY SUCH MATTER SHALL BE THE IMMEDIATE,
    UNILATERAL TERMINATION OF THIS AGREEMENT.
  contact:
    name: 'NASA Ames Research Center, Aviation Systems Division'
    url: 'https://utm.arc.nasa.gov/'
    email: joseph.rios@nasa.gov
  license:
    name: NASA Open Source Agreement
    url: 'https://ti.arc.nasa.gov/opensource/nosa/'

host: uss.defined.url
basePath: /
schemes:
  - https
securityDefinitions:
  ussapi_security:
    type: oauth2
    description: A write scope allows reading.
    tokenUrl: 'https://utm.defined.host/oauth/token'
    flow: application
    scopes:
      'utm.nasa.gov_read.operation': Subject can read operational data such as USS Instance data
      'utm.nasa.gov_write.operation': Subject can read, create, and update operational data such as USS Instance data
      'utm.nasa.gov_read.message': Subject can read message data such as UTM Message and Negotiations
      'utm.nasa.gov_write.message': Subject can read, create, and update message data such as UTM Message and Negotiations
      'utm.nasa.gov_read.publicsafety': Subject can read operations that are designated public safety operations.
      'utm.nasa.gov_write.publicsafety': Subject can read, create, and update operations that are designated public safety operations.
      'utm.nasa.gov_read.constraint': Subject can read UTM constraint data
      'utm.nasa.gov_write.constraint': Subject can read, create, and update UTM constraint data. This means that the Subject can define areas that restrict other operations.
      'utm.nasa.gov_read.conflictmanagement':  Subject can read conflict management data.
      'utm.nasa.gov_write.conflictmanagement':  Subject can read and write conflict management data.
paths:
  '/uvrs/{message_id}':
    put:
      tags:
        - A. Required Endpoints
      summary: Allow UAS Volume Reservations (UVRs) to be submitted from authorized entities.
      description: >-
        Allow UAS Volume Reservations (UVRs) to be submitted from authorized entities.
        For validation purposes:
          {message_id} in path == UASVolumeReservation.message_id of body data
      security:
        - ussapi_security:
            - utm.nasa.gov_write.constraint
  '/utm_messages/{message_id}':
    put:
      tags:
        - A. Required Endpoints
      summary: Allow other authorized entities to send a message to this USS.
      description: >-
        Allows another USS or FIMS to PUT a message to this USS.
        For validation purposes:
          {message_id} in path == UTMMessage.message_id of body data
      security:
        - ussapi_security:
            - utm.nasa.gov_write.message
  '/uss/{uss_instance_id}':
    put:
      tags:
        - A. Required Endpoints
      summary: Share USS Instance data
      description: >-
        As per the USS Discovery Service specification, this endpoint is for
        receiving messages about the USS Network from the USS Discovery
        Service.  For example, when a new USS Instance is registered, that
        announcement would come to this endpoint.

        For validation purposes:
          {uss_instance_id} in path == UssInstance.uss_instance_id of body data
      security:
        - ussapi_security:
            - utm.nasa.gov_write.operation
  '/negotiations/{message_id}':
    put:
      tags:
        - A. Required Endpoints
      summary: Allow other USSs to submit a negotiation request
      description: >-
        A PUT to the negotiations endpoint is interpreted as a request for
        alteration in an existing operation managed by the receiving USS.  The
        requesting USS supplies a GUFI that references the operation that may be
        altered if the request is granted by the receiving USS.

        For validation purposes:
          {message_id} in path == NegotiationMessage.message_id in body data
      security:
        - ussapi_security:
            - utm.nasa.gov_write.message
  '/positions/{position_id}':
    put:
      tags:
        - A. Required Endpoints
      summary: Share position information.
      description: >-
        Providing position reports to others may allow other USSs to anticipate
        events.  The USS managing the operation has created the position ID.

        For validation purposes:
          {position_id} in path == Position.enroute_positions_id of body data
      security:
        - ussapi_security:
            - utm.nasa.gov_write.operation
  /operations:
    get:
      tags:
        - A. Required Endpoints
      summary: Request information regarding Operations
      description: Allows querying for Operation data. Returns an empty list if the query returns nothing.
      security:
        - ussapi_security:
            - utm.nasa.gov_write.operation
            - utm.nasa.gov_read.operation
  '/operations/{gufi}':
    get:
      tags:
        - A. Required Endpoints
      summary: Retrieve an operation by GUFI.
      description: Retrieve an operation by GUFI.  Returns 404 if gufi is not found.
      security:
        - ussapi_security:
            - utm.nasa.gov_write.operation
            - utm.nasa.gov_read.operation
    put:
      tags:
        - A. Required Endpoints
      summary: 'Announce a new, or update an already announced operation.'
      description: >-
        Announce an Operation to another USS, either initial Operation or an
        update to the Operation. The Operation's owner creates the ID.
      security:
        - ussapi_security:
            - utm.nasa.gov_write.operation
  '/enhanced/operations/{gufi}':
    get:
      tags:
        - A. Required Endpoints
      summary: Retrieve an operation by GUFI, including details relevant to safety and security.
      description: >-
        Retrieve an operation by GUFI.  Returns 404 if gufi is not found.
        Similar to '/operations/{gufi}' except
        all data tagged x-utm-data-accessibility <= SAFETY is returned.

        Note that there is currently no GET on '/enhanced/operations/' without
        specifying a GUFI.  If general seraching for operations is required, then
        a GET on '/operations' may be performed, followed by individual GETs to
        this endpoint for enhanced data access.

      security:
        - ussapi_security:
            - utm.nasa.gov_read.publicsafety
            - utm.nasa.gov_write.publicsafety
    put:
      tags:
        - A. Required Endpoints
      summary: 'Announce a new, or update an already announced ENHANCED operation.'
      description: >-
        Announce an Operation to another USS, either initial Operation or an
        update to the Operation. The Operation's owner creates the ID.

        This is the ENHANCED version of the nominal /operations/{gufi} endpoint.
        A USS receiving an operation on this endpoint MUST validate that PriorityElements.status == PUBLIC_SAFETY with an appropriate severity.

        In the future there may be several use cases for the this endpoint.
        Currently a single use case is required to be supported by USSs.

        ## Writing a public safety operation

        Public safety operations can only be operated by authorized agencies.  The
        identitiy management of those agencies and individuals within them will
        have more requirements than are levied on nominal USSs.  Thus the ability
        to manage those operations is limited to USSs that undergo additional
        checkout processes.  Successful completion of those processes allows for
        a USS to earn an additional Role (USS_PUBLIC_SAFETY) within UTM managing
        public safety ops.

        This role provides access to additional scopes, including utm.nasa.gov_write.publicsafety
        which is required to write to this endpoint.

        A public safety operation that ceases to be a public safety operation
        should CLOSE the operation as announced on this endpoint after creating
        a non-public safety operation on the nominal endpoint.  Note this means
        that the operation would be already be in the air when becoming a "new"
        nominal operation.  In addition, there will be a period of time during
        which this operation will have 2 GUFIs and 2 plans. The USS should aid
        the operator in minimizing this period of time (ideally to less than, say,
        10 seconds).  This approach ensures that all operations announced on this
        PUT endpoint have the same PriorityElement requirements.

        A nominal operation that becomes a public safety operation should
        follow a similar procedure as above.  CLOSE the nominal operation after
        announcing a new public safety operation on this endpoint.

      security:
        - ussapi_security:
            - utm.nasa.gov_write.publicsafety